name: FE codedeploy

# main 브런치에 push가 되면 아래의 flow가 실행됩니다. cicde test
on:
  pull_request:
    branches: [ "release-fe" ]
   
# flow에서 사용할 변수 같은 느낌입니다.
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: codesquad-s3
  CODE_DEPLOY_APPLICATION_NAME: codesquad-project
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: web-cd
  working-directory: ./fe # 이 코드는 제 프로젝트 경로를 맞춰주기 위해 적어주었습니다. 필요하시면 적으세요 !

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest


    steps:

      
    # AWS 인증
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3
    
    # 2) node 셋팅
    - name: Set node@v1
      uses: actions/setup-node@v3
      
    - name: check Node v
      run: node -v
    
    - name: Install npm
      run: sudo apt install npm

    - name: check npm
      run: npm -v

    - name: install dependency
      run: npm install
      working-directory: ${{ env.working-directory }}

    - name: install CI
      run: npm ci
      working-directory: ${{ env.working-directory }}
    
    - name: Generate build
      run: npm run build
      working-directory: ${{ env.working-directory }}


        
    # AWS S3에 업로드
    - name: Upload to AWS S3
      run: |
        aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --ignore-hidden-files \
          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --source .
          
    # AWS EC2에 Deploy
    - name: Deploy to AWS EC2 from S3
      run: |
        aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip